/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC3156FlashBorrowerUpgradeable } from "./IERC3156FlashBorrowerUpgradeable";
export type { IERC3156FlashLenderUpgradeable } from "./IERC3156FlashLenderUpgradeable";
