/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { Profiles, ProfilesInterface } from "../../contracts/Profiles";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212207f6e54176ae8793ca84b572444b5be9a0b7ef597765320a91013018abafc010564736f6c63430008090033";

type ProfilesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ProfilesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Profiles__factory extends ContractFactory {
  constructor(...args: ProfilesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Profiles> {
    return super.deploy(overrides || {}) as Promise<Profiles>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Profiles {
    return super.attach(address) as Profiles;
  }
  override connect(signer: Signer): Profiles__factory {
    return super.connect(signer) as Profiles__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ProfilesInterface {
    return new utils.Interface(_abi) as ProfilesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Profiles {
    return new Contract(address, _abi, signerOrProvider) as Profiles;
  }
}
