/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC3156FlashBorrowerUpgradeable__factory } from "./IERC3156FlashBorrowerUpgradeable__factory";
export { IERC3156FlashLenderUpgradeable__factory } from "./IERC3156FlashLenderUpgradeable__factory";
